### model
model_name_or_path: /jiangwenhao/Qwen2.5-VL-7B-Instruct
output_dir: saves/qwen2_5vl-7b/full/smartagentV2-multiturn
num_train_epochs: 5
logging_steps: 10
save_strategy: epoch
eval_strategy: steps
eval_steps: 50
save_total_limit: 5
dataset: smartagentV2-multiturn
eval_dataset: smartagentV2-val-singleturn
load_best_model_at_end: False
metric_for_best_model: eval_loss
image_max_pixels: 2000000
image_min_pixels: 40000
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset

template: qwen2_vl
cutoff_len: 32768
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 0

### output

plot_loss: true
overwrite_output_dir: true
save_only_model: True
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]


### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-5

lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
do_eval: true
val_size: 0.0
per_device_eval_batch_size: 1

greater_is_better: false
